name: PHP Static Analysis
on:
  workflow_dispatch:
  push:
    branches: ['main']
  pull_request:
    branches-ignore:
    - 'dependabot/npm_and_yarn/*'
    - 'dependabot/composer/*'

jobs:
  composer_install:
    runs-on: "ubuntu-latest"
    name: Installing Dependencies
    steps:
      - uses: actions/checkout@v4
      - name: Get Composer Cache Directory
        id: composer-cache
        run: |
          echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT
      - uses: actions/cache@v4
        with:
          path: |
            ${{ steps.composer-cache.outputs.dir }}
            ./vendor
          key: composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: composer-
      - name: setup php
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3
          extensions: dom, curl, libxml, mbstring, zip, fileinfo
      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"
      - name: Install Dependencies
        run: |
          composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
      - name: Generate key
        run: php artisan key:generate
  phpstan:
    runs-on: "ubuntu-latest"
    name: PHP Static Analysis
    needs: composer_install
    steps:
      - uses: actions/checkout@v4
      - name: setup php
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3
          extensions: dom, curl, libxml, mbstring, zip, fileinfo
      - name: Get Composer Cache Directory
        id: composer-cache
        run: |
          echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT
      - uses: actions/cache@v4
        with:
          path: |
            ${{ steps.composer-cache.outputs.dir }}
            ./vendor
          key: composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: composer-
      - name: "Running Static Analysis"
        run: |
          vendor/phpstan/phpstan/phpstan --no-progress --memory-limit=256M analyze
