name: Laravel Linting with Pint
on:
  workflow_dispatch:
  pull_request:
    branches-ignore:
      - 'dependabot/npm_and_yarn/*'
      - 'dependabot/composer/*'

jobs:
  phplint:
    runs-on: "ubuntu-latest"
    name: Laravel Pint
  # You may pin to the exact commit or the version.
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - name: "Laravel Pint"
        uses: aglipanci/laravel-pint-action@2.3.0
        with:
          preset: laravel
          verboseMode: true
      - name: Git Auto Commit
        uses: stefanzweifel/git-auto-commit-action@v4.16.0
        with:
          commit_message: PHP Linting (Pint)
          skip_fetch: true
          repository: .
          branch: ${{ github.head_ref }}
          status_options: '--porcelain'
          file_pattern: '*.php'
