name: Vitest
on:
  workflow_dispatch:
  push:
    branches-ignore:
      - 'dependabot/npm_and_yarn/*'
      - 'dependabot/composer/*'

jobs:
  vitest:
    runs-on: "ubuntu-latest"
    name: "Vitest"
  # You may pin to the exact commit or the version.
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - name: NPM Install
        run: npm ci
      - name: Vitest
        run: npm run test:run
